services:

  pgdatabase:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    ports:
      - '5432:5432'
    volumes:
      - '/docker-entrypoint-initdb.d'